name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Create resources folder
        run: mkdir -p tikz/resource
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: astro-notebook.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: astro-notebook.pdf

          
